language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- npm install -g grunt-cli
addons:
  sauce_connect: true
env:
  global:
  - secure: Z2owUW/1mCKcHRsIlNVn5K71FTtKr1o2APrm5FhFnHhszp3toq4Egk97JdFvXtVWh80CjPJBlUoCX1LGCccIWu7x0veJTi3hqpPw8XN1+fsmJSR5iHP7r1M4n/fjT03WC+6TxhCWiPUd1kYky3i3cyM1Q0l54KfFDWvBKREyCCU=
  - secure: eyJX6kqHK2VJZT+8Qh/mKtfduXem9BVseKVW1bhMaZIoo5baMolpgEXUpNEN93WSzcqa4F9Rc+qrBGMAfqcDyQl0re+O1CxL5EA4XTjdbMMDiXSeakGXMoi580EWOMhoay/EpqOb5Fxwince3kNbHS87qOMpSrJwQk8pk1KRHB0=
